#!/bin/bash

FOUND_ERROR="FALSE"

ROOT_DIR=$(git rev-parse --show-toplevel)
USER_BLACKLIST=~/.gitblacklist
BLACKLIST=$ROOT_DIR/.gitblacklist
LIST=$(git status --porcelain | grep -e '^\s*\(M\|A\)' | grep -v gitblacklist)

LAST_FILENAME=""

function checkBlackList(){
    blacklist_file=$1
    filepath=$2
    filename=$3

    if [ -f $blacklist_file ]; then
        while IFS= read -r CHECK
        do
            if [ "$CHECK" != "" ]; then

                #echo "Checking for '$CHECK' in $FILE_ACTION file: $filename"
                ERRORS=$(grep -in --color "${CHECK}" $filepath >&1)

                if [ "$FOUND_ERROR" = "FALSE" ]; then
                    FOUND_ERROR="TRUE"
                    echo "These errors were found in staged files:"
                fi

                if [ "$ERRORS" != "" ]; then

                    if [ "$filename" != "$LAST_FILENAME" ]; then
                        LAST_FILENAME="$filename"
                        echo "$filename:"
                    fi
                    echo "    $ERRORS"
                fi
            fi
        done < $blacklist_file
    fi
}

for FILEPATH in $LIST
do
    if [ $(echo "$FILEPATH" | grep 'M') ]; then
        FILE_ACTION="modified"
    elif [ $(echo "$FILEPATH" | grep 'A') ]; then
        FILE_ACTION="added"
    else
        # if there's no extension, this returns the full filename
        FILENAME="${FILEPATH##*/}"
        BASE="${FILENAME%.[^.]*}"
        EXTENSION="${FILENAME:${#BASE} + 1}"
        if [[ -z "$BASE" && -n "$EXTENSION" ]]; then
            BASE=".$EXTENSION"
            EXTENSION=""
        fi

        checkBlackList $USER_BLACKLIST $FILEPATH $FILENAME

        checkBlackList $BLACKLIST $FILEPATH $FILENAME

        if [ "$EXTENSION" != "$FILEPATH" ]; then
            BLACKLIST_FILE_EXTENSION=$BLACKLIST.$EXTENSION
            USER_BLACKLIST_EXTENSION=$USER_BLACKLIST.$EXTENSION
            checkBlackList $BLACKLIST_FILE_EXTENSION $FILEPATH $FILENAME
            checkBlackList $USER_BLACKLIST_EXTENSION $FILEPATH $FILENAME
        fi
    fi
done

if [ "$FOUND_ERROR" = "TRUE" ]; then
    echo
    echo "Commit rejected, fix errors first."
    exit 1
fi
